Update setup-composer-auth
Update to include github token

diff --git a/compose/bin/setup-composer-auth b/compose/bin/setup-composer-auth
--- a/compose/bin/setup-composer-auth
+++ b/compose/bin/setup-composer-auth
@@ -1,12 +1,17 @@
 #!/usr/bin/env bash
 MAGENTO_USERNAME_PROP="http-basic.repo.magento.com.username"
 MAGENTO_PASSWORD_PROP="http-basic.repo.magento.com.password"
+GITHUB_AUTH_PROP="github-oauth.github.com"
+
 hash composer 2>/dev/null && IS_COMPOSER_ON_HOST=true
 
 PUBLIC_KEY="$(bin/clinotty composer config --global $MAGENTO_USERNAME_PROP 2>/dev/null)"
 PRIVATE_KEY="$(bin/clinotty composer config --global $MAGENTO_PASSWORD_PROP 2>/dev/null)"
 
-if [ -n "$PUBLIC_KEY" ] && [ -n "$PRIVATE_KEY" ]; then
+GITHUB_TOKEN="$(bin/clinotty composer config --global $GITHUB_AUTH_PROP 2>/dev/null)"
+
+
+if [ -n "$PUBLIC_KEY" ] && [ -n "$PRIVATE_KEY" ] && [ -n "$GITHUB_TOKEN"]; then
     echo "Composer auth has already been set up."
     exit 0
 fi
@@ -14,6 +19,7 @@ fi
 if [ "$IS_COMPOSER_ON_HOST" ]; then
     PUBLIC_KEY="$(composer config --global $MAGENTO_USERNAME_PROP 2>/dev/null)"
     PRIVATE_KEY="$(composer config --global $MAGENTO_PASSWORD_PROP 2>/dev/null)"
+    GITHUB_TOKEN="$(composer config --global $GITHUB_AUTH_PROP 2>/dev/null)"
 fi
 
 if [ -z "$PUBLIC_KEY" ] || [ -z "$PRIVATE_KEY" ]; then
@@ -26,12 +32,30 @@ if [ -z "$PUBLIC_KEY" ] || [ -z "$PRIVATE_KEY" ]; then
     exec <&-
 fi
 
+if [ -z "$GITHUB_TOKEN" ]; then
+    exec < /dev/tty
+    echo
+    echo "Composer authentication required (Github Token ):"
+    read -r -p "    Token: " GITHUB_TOKEN
+    echo
+    exec <&-
+fi
+
+
 if [ -z "$PUBLIC_KEY" ] || [ -z "$PRIVATE_KEY" ]; then
     echo "Please setup Composer auth for repo.magento.com to continue." && exit 1
 fi
 
+if [ -z "$GITHUB_TOKEN" ] ; then
+    echo "Please setup Composer auth for Github to continue." && exit 1
+fi
+
 # Output must be piped otherwise file descriptor errors occur. Carriage returns?
 echo "composer config --global http-basic.repo.magento.com ${PUBLIC_KEY} ${PRIVATE_KEY}" | bin/clinotty bash -
+
+# Output must be piped otherwise file descriptor errors occur. Carriage returns?
+echo "composer config --global github-oauth ${GITHUB_TOKEN}" | bin/clinotty bash -
+
 
 # Also make sure alternate auth.json is setup (Magento uses this internally)
 bin/clinotty [ -d "./var/composer_home" ] && bin/clinotty cp /var/www/.composer/auth.json ./var/composer_home/auth.json
